# Created with YamlCreate.ps1 v2.2.8 $debug=NVS1.CRLF.5-1-19041-2364.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: Teradata.TeradataODBCSuite
PackageVersion: 20.00.10.00
PackageLocale: en-US
Publisher: Teradata Corporation
PublisherUrl: https://www.teradata.com/
# PublisherSupportUrl:
# PrivacyUrl:
# Author:
PackageName: ODBC Driver for Teradata - Suite 20.00.10
# PackageUrl:
License: Teradata
LicenseUrl: https://downloads.teradata.com/download/license/download-agreement-teradata-tools-utilities
# Copyright:
# CopyrightUrl:
ShortDescription: ODBC Driver for Teradata - Suite
Description: ODBC Driver for Teradata - Suite
# Moniker:
# Tags:
# ReleaseNotes:
# ReleaseNotesUrl:
# PurchaseUrl:
# InstallationNotes:
# Documentations:
ManifestType: defaultLocale
ManifestVersion: 1.4.0
